### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by H-ishak** [syedali996/conversationsapi#1]
i couldn't install the package via composer .
![image](https://user-images.githubusercontent.com/71776062/230054848-9285e49b-0d72-4e7d-93c7-0bd36bb1aabd.png)

could you please fix it ?

**Comment by syedali996** [comment]
Hey @H-ishak can you kindly share your composer file?

**Comment by H-ishak** [comment]
i found the problem . thanks a lot for your assistance @syedali996
